import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/client/antd.registry';
import './globals.css'

// const roboto = Roboto({
//   weight: ['400', '700'],
//   subsets: ['latin', 'vietnamese'], 
//   display: 'swap', 
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
